language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-monit.gemspec
- gem install sensu-plugins-monit-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: Hf2IGYobTAA1U7BDp7gQxPJG5uacuX1nwy7DkR+dpydMqipzVM7b3VHcF3f/BRO4unkm+ZGWbQwpyHTgL8eg1HCBQf+8R4lrpltBRPKkpdQzmCJfHL6f+dlzTyp7g9iUesRMnf5ywRrY20HV3msTX8f66bwykdHsRpnCa2jvelA=
  gem: sensu-plugins-monit
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    repo: sensu-plugins/sensu-plugins-monit
